### ISSUE TITLE
Implement change visibility timeout in SQS stream

### ISSUE THREAD

**Issue by cnp96** [social9/go-queues#11]
Implement a method
```go
func ChangeVisibilityTimeout(msgId string, timeout int) void
```
in SQS stream to update the message visibility.

**Comment by choudharyanurag** [comment]
Worked on that. Forked the branch and did some work there. 
Please checkout this branch here : https://github.com/choudharyanurag/go-queues.git 


The func can not be created as msgId, because we can grab the message by `asking` sqs for more messages, but we can not ask for a message with message ID (at least as of today). 

So, we need to do it from the place where we have received the message, the `ReceiptHandle` shall not change for the processor. That means, the one who holds the message has got all the authorities around it, the processor may process and delete it. Or may send it back to the queue by `ChangeVisibilityTimeout` .

**Comment by cnp96** [comment]
@choudharyanurag I suppose this change is already merged. If not, please raise a PR or let me know so that I can close this issue.

**Comment by cnp96** [comment]
Issues covered in PR #12
